openapi: 3.0.3
info:
  description: |
    API documentation for channel opening request from a Lightning Network Service Provider (LSP).
    
  version: "1"
  title: "LSP Spec 1"
tags:
- name: "Refund"
  description: "Extension: `refunds`"


paths:           
  /lsp/channels/{id}/refund:
    get:
      tags:
      - Refund
      summary: "Get information about refunds."
      description: "Get information about refunds."
      operationId: "get-channel-refund"

      parameters:
        - in: path
          name: id
          description: "Order id"
          required: true
          schema:
              type: string
      responses:
        "200":
          description: "Refund information"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelRefundGetResponse"
        "404":
          description: "Not found"
          
    post:
      tags:
      - Refund
      summary: "Refunds a paid offer."
      description: "Refunds a paid offer. Can be before the channel has been opened or due to an issue."
      operationId: "post-channel-refund"
      parameters:
        - in: path
          name: id
          description: "Order id."
          required: true
          schema:
              type: string
      requestBody:
          description: "Information needed to refund the payment."
          required: true
          content:
              application/json:
                  schema:
                      $ref: '#/components/schemas/ChannelRefundPostRequest'
      responses:
        "200":
          description: "Success"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelRefundPostResponse"
        "400":
          description: "Validation error"
        "404":
          description: "Not found"
        "412":
          description: "Channel refund failed"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelRefundPostResponse"
    
components:
    schemas:

      ChannelRefundGetResponse:
        type: "object"
        properties:
          refund_state:
            type: string
            enum:
              - AVAILABLE
              - PAID_OUT
              - IN_FLIGHT # Stuck payment. Resolves later.
              - UNAVAILABLE
            description: "Is a refund possible?"
            example: AVAILABLE
          amounts:
            type: object
            nullable: true
            properties:
              lightning:
                type: integer
                description: "Satoshi available for refunds on lightning."
                example: 2008888
              onchain:
                type: integer
                description: "Satoshi available for refunds onchain."
                example: 2005000
          paid_to:
           type: string
           description: "Either Lightning invoice or onchain address where the refund has been paid to."
           nullable: true
           example: null
          paid_ts:
            type: integer
            description: "Number of seconds since epoch when this refund was given."
            example: null
            nullable: true
                
      ChannelRefundPostRequest:
        type: "object"
        properties:
          lightning_invoice: # Either or onchain_address
            type: string
            nullable: true
            description: "Lightning invoice where the refund should be paid to. Invoice should have the same amount as the offered refund."
            example: "lnbc252u1p3aht9ysp580g4633gd2x9lc5al0wd8wx0mpn9748jeyz46kqjrpxn52uhfpjqpp5qgf67tcqmuqehzgjm8mzya90h73deafvr4m5705l5u5l4r05l8cqdpud3h8ymm4w3jhytnpwpczqmt0de6xsmre2pkxzm3qydmkzdjrdev9s7zhgfaqxqyjw5qcqpjrzjqt6xptnd85lpqnu2lefq4cx070v5cdwzh2xlvmdgnu7gqp4zvkus5zapryqqx9qqqyqqqqqqqqqqqcsq9q9qyysgqen77vu8xqjelum24hgjpgfdgfgx4q0nehhalcmuggt32japhjuksq9jv6eksjfnppm4hrzsgyxt8y8xacxut9qv3fpyetz8t7tsymygq8yzn05"
          onchain_address: # Either or lightning_invoice
            type: string
            nullable: true
            description: "Onchain address where the refund should be paid to."
            example: "bc1p5uvtaxzkjwvey2tfy49k5vtqfpjmrgm09cvs88ezyy8h2zv7jhas9tu4yr"
                 
      ChannelRefundPostResponse:
        type: "object"
        properties:
          success:
            type: boolean
            description: "Indicates if the channel has been opened."
            example: true
          message:
            type: string
            description: "Human readable message."
            example: "ok"
          fail_reason:
            type: string
            nullable: true
            description: "Reason the refund failed."
            enum:
              - PAYMENT_FAILED # For example, path not found
              - REJECTED_BY_LSP # LSP rejected node.
              - UNSUPPORTED
            example: null

          
          
          
          
            