openapi: 3.0.3
info:
  description: |
    API documentation for channel opening request from a Lightning Network Service Provider (LSP). JIT_CHANNELS.
    
  version: "1"
  title: "LSP Spec 1"
tags:
- name: "JIT"
  description: "Extension: `jit_channels`."



paths:

  /lsp/channels/{id}/jit:
    get:
      tags:
      - JIT
      summary: "Get information about registered JIT node."
      description: |
        Get information about registered JIT node. Feature: `jit_channels`.
      operationId: "get-channel-jit"

      parameters:
        - in: path
          name: id
          description: "Order id"
          required: true
          schema:
              type: string
      responses:
        "200":
          description: "Channel information"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelJITResponse"
        "404":
          description: "Not found"
    post:
      tags:
      - JIT
      summary: "Register the JIT node."
      description: |
        Register JIT node. Feature: `jit_channels`.
      operationId: "post-channel-jit"

      parameters:
        - in: path
          name: id
          description: "Order id"
          required: true
          schema:
              type: string
      requestBody:
          description: "Information needed to connect to the node."
          required: true
          content:
              application/json:
                  schema:
                      $ref: '#/components/schemas/ChannelJITRequest'
      responses:
        "200":
          description: "Channel information"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelJITResponse"
        "404":
          description: "Not found"
                  
components:
    schemas:
      ChannelJITRequest:
        type: "object"
        required:
          - node_connection_string
        properties:
          node_connection_string:
            description: "The node connection string that the channel will be opened to in case of an incoming payment."
            example: "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@3.33.236.230:9735"
            type: "string"

      ChannelJITResponse:
        type: "object"
        properties:
          fee_per_payment:
            description: "For intercepted payment of fee, fee in satoshi taken from each payment until fee is paid."
            type: integer
            example: 50
          route_hint:
            type: object
            nullable: true
            properties:
              scid:
                description: "The short_channel_id the user puts in the route hint of the invoice. See BOLT#7 for scid definition."
                example: "733904x1451x0"
                type: "string"
              node_id:
                description: "The node_id the user puts in the route hint of the invoice."
                example: "031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0"
                type: "string"
          registered_node_connection_string:
            description: "The registerd node id that the channel will be opened to in case of an incoming payment."
            example: "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@3.33.236.230:9735"
            type: "string"
            nullable: true

          
          
          
          
          
            