openapi: 3.0.3
info:
  description: |
    API documentation for channel opening request from a Lightning Network Service Provider (LSP). Base API.
    

    ### Extensions
    The api is split in to the base api and extensions.
    All supported extensions are listed in the general API info endpoint.
    Extensions can add additional endpoints or fields.

  version: "2"
  title: "LSP Spec 1"
tags:
- name: "API Info"
- name: "Channel Request"


paths:
  /lsp/channels:
    get:
      tags:
      - "API Info"
      summary: "Get general API information."
      description: |
        Get general information about this API and supported extensions.
        
      operationId: "channel-order-info"
      responses:
        "200":
          description: |
            ## Extensions
            
            ### local_balance
            Indicates if the LSP is willing to push satoshi to the receiver side.

            ### onchain_payments
            Indicates if the LSP is willing to receive payments onchain.
            `min_satoshi` is the number of satoshi that are required for an onchain payment.
            
          content:
              application/json:
                schema:
                    $ref: "#/components/schemas/ChannelApiInfo"
                example:
                  local_balance:
                    version: 1
                  onchain_payments:
                    min_satoshi: 50000
                    version: 1
  
    post:
      tags:
      - "Channel Request"
      summary: "Requests a new channel order from the LSP."
      description: |
        This endpoint accepts arguments for a channel with a specific size and duration and returns the order information.
        
      operationId: "new-channel-request"
      requestBody:
          description: "Information needed to create your new deposit invoice."
          required: true
          content:
              application/json:
                  schema:
                      $ref: '#/components/schemas/ChannelOrderRequest'
      responses:
        "201":
          description: "Created"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelOrderResponse"
        "400":
          description: "Validation error."
              
  /lsp/channels/{id}:
    get:
      tags:
      - Channel Request
      summary: "Get information about a channel order."
      description: "Get information about a channel order"
      operationId: "get-channel-order"

      parameters:
        - in: path
          name: id
          description: "Order id"
          required: true
          schema:
              type: string
      responses:
        "200":
          description: "Channel information"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Order"
        "404":
          description: "Not found"
          
  /lsp/channels/{id}/open:
    post:
      tags:
      - "Channel Request"
      summary: "Opens a previously paid channel."
      description: |
        This endpoint accepts arguments to open a channel to a specific node. It performs an actual channel open and returns success/error.
      operationId: "open-channel-request"
      parameters:
        - in: path
          name: id
          description: "Order id."
          required: true
          schema:
              type: string
      requestBody:
          description: "Information needed to open the channel."
          required: true
          content:
              application/json:
                  schema:
                      $ref: '#/components/schemas/ChannelOpenRequest'
      responses:
        "201":
          description: "Success"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelOpenResponse"
        "400":
          description: "Validation error"
        "404":
          description: "Not found"
        "412":
          description: "Channel open failed"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelOpenResponse"


components:
    schemas:
      ChannelApiInfo:
        type: "object"
        properties:
          version:
            type: integer
            description: "Version of this api. See https://github.com/BitcoinAndLightningLayerSpecs/lsp"
            example: 2
          extensions:
            type: object
            additionalProperties:
              $ref: "#/components/schemas/Extension"
          website:
            type: string
            description: "Website that provides devs a way to get in contact and/or TOS."
            example: "https://blocktank.to/contact"

      # ChannelApiInfo String Extension      
      BaseExtension:
        type: object
        properties:
          version:
            type: integer
            example: 1
            default: 1
            nullable: true
            description: Version of this extension. Integer starting at 1 counting up.
        
      OnchainPaymentExtension:
        # Extends BaseExtension
        allOf:
          - $ref: "#/components/schemas/BaseExtension"
          - type: object
            properties:
              min_satoshi:
                type: string
                description: "Minimal number of satoshi required to be eligable for an onchain payment."
                example: 50000

      Extension:
      # One of these types need to match
        oneOf:
          - $ref: "#/components/schemas/BaseExtension"
          - $ref: "#/components/schemas/OnchainPaymentExtension"
    
      ChannelOrderRequest:
        type: "object"
        required:
          - remote_balance
        properties:
          remote_balance:
            type: integer
            description: "Inbound liquidity amount in satoshis. Funds are at the LSP side."
            example: 5000000
            minimum: 0
          local_balance:
            type: integer
            description: "Outbound liquidity amount in satoshis. Funds are at the user side."
            default: 0
            example: 2000000
            minimum: 0
          onchain_fee_rate:
            type: number
            description: "On-chain fee rate of the channel opening transaction in satoshis per vbyte."
            minimum: 1
          channel_expiry:
            type: integer
            description: "Channel expiration in weeks."
            minimum: 1
            example: 12
          coupon_code:
            type: string
            description: "Coupon code to get a discount on the purchase."
            default: ''
            
      ChannelOrderResponse:
        type: "object"
        properties:
          id:
            type: string
            description: "An lsp generated order id used to look-up the status of this request."
            example: bb4b5d0a-8334-49d8-9463-90a6d413af7c
          fee_total:
            type: integer
            description: "The total fee in satoshi the LSP will charge to open this channel."
            example: 8888
            minimum: 0
          order_total:
            type: integer
            description: "fee_total plus the local_balance requested in satoshi."
            example: 2008888
            minimum: 0
          order_expiry_ts:
            description: "Number of seconds since epoch when this order can still be paid."
            type: integer
            example: 1672661897
          ln_invoice:
            type: string
            description: "A lightning bolt11 invoice to pay the fee for this channel open."
            example: "lnbc252u1p3aht9ysp580g4633gd2x9lc5al0wd8wx0mpn9748jeyz46kqjrpxn52uhfpjqpp5qgf67tcqmuqehzgjm8mzya90h73deafvr4m5705l5u5l4r05l8cqdpud3h8ymm4w3jhytnpwpczqmt0de6xsmre2pkxzm3qydmkzdjrdev9s7zhgfaqxqyjw5qcqpjrzjqt6xptnd85lpqnu2lefq4cx070v5cdwzh2xlvmdgnu7gqp4zvkus5zapryqqx9qqqyqqqqqqqqqqqcsq9q9qyysgqen77vu8xqjelum24hgjpgfdgfgx4q0nehhalcmuggt32japhjuksq9jv6eksjfnppm4hrzsgyxt8y8xacxut9qv3fpyetz8t7tsymygq8yzn05"
          btc_address:
            type: string
            nullable: true
            description: "An on-chain bitcoin address to pay the fee for this channel open."
            example: "bc1p5uvtaxzkjwvey2tfy49k5vtqfpjmrgm09cvs88ezyy8h2zv7jhas9tu4yr"
          request:
            $ref: "#/components/schemas/ChannelOrderRequest"
            
      Order:
        type: "object"
        properties:
          id:
            type: string
            description: "An lsp generated order id used to look-up the status of this request"
            example: bb4b5d0a-8334-49d8-9463-90a6d413af7c
          created_at:
            description: "Number of seconds since epoch when this order was created."
            type: "number"
            example: 1675340297
          state:
            description: "The state of the order."
            type: "string"
            enum:
              - AWAITING_PAYMENT
              - OFFER_EXPIRED
              - PENDING_CHANNEL_OPEN
              - COMPLETED
            example: COMPLETED
          request:
            $ref: "#/components/schemas/ChannelOrderRequest"
          payment:
            type: object
            properties:
              state:
                description: "The state of the payment."
                type: "string"
                enum:
                  - CREATED
                  - UNDER_FUNDED
                  - PAID
                  - REFUNDED
                example: PAID
              order_expiry_ts:
                description: "Number of seconds since epoch when this order can still be paid."
                type: integer
                example: 1672661897
              fee_total:
                description: "The total fee the lsp will charge to open this channel in satoshi."
                type: integer
                example: 8888
              order_total:
                description: "fee_total plus the local_balance requested in satoshi."
                type: integer
                example: 2008888
              amount_paid:
                description: "Amount paid by client so far in satoshi."
                type: number
                example: 1200
              ln_invoice:
                description: "A lightning bolt11 invoice to pay the fee for this channel open."
                type: "string"
                example: "lnbc252u1p3aht9ysp580g4633gd2x9lc5al0wd8wx0mpn9748jeyz46kqjrpxn52uhfpjqpp5qgf67tcqmuqehzgjm8mzya90h73deafvr4m5705l5u5l4r05l8cqdpud3h8ymm4w3jhytnpwpczqmt0de6xsmre2pkxzm3qydmkzdjrdev9s7zhgfaqxqyjw5qcqpjrzjqt6xptnd85lpqnu2lefq4cx070v5cdwzh2xlvmdgnu7gqp4zvkus5zapryqqx9qqqyqqqqqqqqqqqcsq9q9qyysgqen77vu8xqjelum24hgjpgfdgfgx4q0nehhalcmuggt32japhjuksq9jv6eksjfnppm4hrzsgyxt8y8xacxut9qv3fpyetz8t7tsymygq8yzn05"
              btc_address:
                description: "An on-chain bitcoin address to pay the fee for this channel open."
                type: "string"
                nullable: true
                example: 'bc1p5uvtaxzkjwvey2tfy49k5vtqfpjmrgm09cvs88ezyy8h2zv7jhas9tu4yr'
              onchain_payments:
                description: "A list of payments received to btc_address onchain."
                nullable: true
                type: "array"
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                      description: "Transaction id"
                      example: '0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae'
                    out_point:
                      type: integer
                      example: 0
                    amount:
                      type: integer
                      description: "Transaction amount in satoshi"
                      example: 1200
                    zero_conf:
                      type: boolean
                      description: "If payment was accepted as zero confirmation"
                      example: false
          channel:
            type: object
            nullable: true
            properties:
              state:
                type: string
                enum:
                  - OPENING
                  - OPENED
                  - CLOSING
                  - CLOSED
              opened_ts:
                description: "Number of seconds since epoch when the channel has been opened."
                type: integer
                example: 1672661897
              open_transaction:
                description: "The txid of the channel funding tx once it is broadcast."
                type: "string"
                example: '0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae:1'
              scid:
                type: string
                description: "Short channel id of the channel. Only available after channel confirmed."
                example: '643904x1419x1'
                nullable: true
              expiry_ts:
                description: "Number of seconds since epoch when the channel can be closed. Only available after channel is opened."
                type: integer
                example: 1672661899
                nullable: true
              closing_transaction:
                description: "The txid of the channel closing tx once it is broadcast."
                type: "string"
                nullable: true
                example: '0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae:1'
              closed_ts:
                description: "Number of seconds since epoch when the channel has been closed."
                type: integer
                example: 1672661898
                nullable: true
              node_id:
                description: "The node id of the customer node."
                type: "string"
                example: "03d4e028a0d4a90868ec202ab684fb0085779defea9ca7553e06146557631eec20@xahwmijytzsgjeo5z2spaj2kcmbawdw2bn7kejtbftvazhhvcn5wloqd.onion:9735"
              lsp_node_id:
                description: "The node id of the lsp node."
                type: "string"
                example: "0296b2db342fcf87ea94d981757fdf4d3e545bd5cef4919f58b5d38dfdd73bf5c9@34.79.58.84:9735"
          
      ChannelOpenRequest:
        type: "object"
        required:
          - announce_channel
          - node_connection_string
        properties:
          announce_channel:
            type: boolean
            description: "If the channel should be announced to the network. Also known as private/public channels."
            example: true
          node_connection_string:
            type: string
            description: "Node connection string to open the channel to."
            example: "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@3.33.236.230:9735"
            
      ChannelOpenResponse:
        type: "object"
        properties:
          success:
            type: boolean
            description: "Indicates if the channel has been opened."
            example: true
          message:
            type: string
            description: "Human readable message."
            example: "ok"
          fail_reason:
            type: string
            nullable: true
            description: "Reason the channel couldn't be opened."
            enum:
              - CHANNEL_REJECTED_BY_DESTINATION # For example wumbo not enabled.
              - PEERING_FAILED # Couldn't establish a peer connection
              - REJECTED_BY_LSP # LSP rejected node.
              - PAYMENT_REQUIRED
              - ALREADY_OPEN
            example: null
          lsp_node_connection_string:
            type: string
            nullable: true
            description: "Node connection string that tried to connect."
         
          
          
          
          
            