openapi: 3.0.3
info:
  description: |
    API documentation for channel opening request from a Lightning Network Service Provider (LSP). LNURL_LUD2.
    
  version: "1"
  title: "LSP Spec 1"
tags:
- name: "LNURL"
  description: "Extension: `lnurl_lud2`."



paths:                    
  /lsp/channels/{id}/lnurl:
    get:
      tags:
      - LNURL
      summary: "Get LNURL LUD2."
      description: |
        Get the LNURL LUD2 string. Extension: `lnurl_lud2`.
      operationId: "get-channel-lnurl-lud2"

      parameters:
        - in: path
          name: id
          description: "Order id"
          required: true
          schema:
              type: string
      responses:
        "200":
          description: "Channel information"
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ChannelOpenLnurlResponse"
        "404":
          description: "Not found"
                  
components:
    schemas:
      ChannelOpenLnurlResponse:
        type: "object"
        properties:
          lnurl_channel:
            type: string
            description: "Encoded LNURL LUD2 string."
            example: "lnurl1dp68gurn8ghj7mrww4exctt5dahkccn00qhxget8wfjk2um0veax2un09e3k7mf0w5lhz0fevvunqcnzxuckxd3n8ymn2ef5ve3kyvrx8qmngc33vymkzvenvesnscm9xuunjwrzxgcxxvrrvcmxgvtyvvmkyc33vsmnjd3svgckzcrx382"



          
          
          
          
          
            